@api=http://localhost:8888

### Add a new user
POST {{api}}/users
Content-type: application/json

{
    "name":"sobhan",
    "email":"sobhan2007f@gmail.com",
    "password":"sobhan15243"
}

### find user
GET {{api}}/users/fvdv0gecrt0u

### delete user
DELETE {{api}}/users/fvdv0gecrt0u
Content-type: application/json
{
    "name":"sobhan",
    "email":"sobhan2007f@gmail.com",
    "password":"sobhan15243"
} 

### sent a massage
POST {{api}}/message
Content-Type:application/json

{
    "chat_id":1,
    "sender_id":647564845505384,
    "text":"salam"
}

### Get chat history
GET {{api}}/chat/1/messages